
stages:
  - pre_requisites
  - build
  - deploy

variables:
  AWS_PRIVATE_IP: "172.31.23.70"  #Change to your private or public IP

before_script:
  - 'which ssh-agent || (apt-get update -y && apt-get install -y openssh-client)'
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -H "$AWS_PRIVATE_IP" >> ~/.ssh/known_hosts

pre_requisites:
  stage: pre_requisites
  tags:
    - agent
    - cicd
  script:
    - |
      ssh -o StrictHostKeyChecking=no ubuntu@"$AWS_PRIVATE_IP" << 'EOF'
        rm -rf /home/ubuntu/Course-section6*
        git clone https://gitlab.com/baljeesi-group/Course-section6-main.git
        cd Course-section6-main
        chmod +x build.sh
        chmod +x deploy.sh
      EOF

build:
  stage: build
  tags:
    - agent
    - cicd
  needs: ["pre_requisites"]
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@"$AWS_PRIVATE_IP" "bash /home/ubuntu/Course-section6-main/build.sh"

deploy:
  stage: deploy
  tags:
    - agent
    - cicd
  needs: ["build"]
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@"$AWS_PRIVATE_IP" "bash /home/ubuntu/Course-section6-main/deploy.sh"
